project_id = "swipchvhpwdomewoxivp"

[functions.create-user]
verify_jwt = false

[functions.send-request-notification]
verify_jwt = false

[functions.generate-insights]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-deactivate-user]
verify_jwt = true
